/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TransfersTransferIdRouteImport } from './routes/transfers.$transferId'
import { Route as LoansNewRouteImport } from './routes/loans.new'
import { Route as LoansLoanIdRouteImport } from './routes/loans.$loanId'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminLoansRouteImport } from './routes/admin.loans'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminTransfersNewRouteImport } from './routes/admin.transfers.new'
import { Route as AdminClientsUserIdRouteImport } from './routes/admin.clients.$userId'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransfersRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersTransferIdRoute = TransfersTransferIdRouteImport.update({
  id: '/$transferId',
  path: '/$transferId',
  getParentRoute: () => TransfersRoute,
} as any)
const LoansNewRoute = LoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansLoanIdRoute = LoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/admin/verify',
  path: '/admin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoansRoute = AdminLoansRouteImport.update({
  id: '/admin/loans',
  path: '/admin/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/admin/clients/',
  path: '/admin/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransfersNewRoute = AdminTransfersNewRouteImport.update({
  id: '/admin/transfers/new',
  path: '/admin/transfers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsUserIdRoute = AdminClientsUserIdRouteImport.update({
  id: '/admin/clients/$userId',
  path: '/admin/clients/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/admin/loans': typeof AdminLoansRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/new': typeof LoansNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/admin/': typeof AdminIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/transfers/new': typeof AdminTransfersNewRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/new': typeof LoansNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/admin': typeof AdminIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/transfers/new': typeof AdminTransfersNewRoute
  '/admin/clients': typeof AdminClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/admin/loans': typeof AdminLoansRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/new': typeof LoansNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/admin/': typeof AdminIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/transfers/new': typeof AdminTransfersNewRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/settings'
    | '/transfers'
    | '/admin/loans'
    | '/admin/verify'
    | '/loans/$loanId'
    | '/loans/new'
    | '/transfers/$transferId'
    | '/admin/'
    | '/transfers/'
    | '/admin/clients/$userId'
    | '/admin/transfers/new'
    | '/admin/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/settings'
    | '/admin/loans'
    | '/admin/verify'
    | '/loans/$loanId'
    | '/loans/new'
    | '/transfers/$transferId'
    | '/admin'
    | '/transfers'
    | '/admin/clients/$userId'
    | '/admin/transfers/new'
    | '/admin/clients'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/settings'
    | '/transfers'
    | '/admin/loans'
    | '/admin/verify'
    | '/loans/$loanId'
    | '/loans/new'
    | '/transfers/$transferId'
    | '/admin/'
    | '/transfers/'
    | '/admin/clients/$userId'
    | '/admin/transfers/new'
    | '/admin/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  TransfersRoute: typeof TransfersRouteWithChildren
  AdminLoansRoute: typeof AdminLoansRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  LoansLoanIdRoute: typeof LoansLoanIdRoute
  LoansNewRoute: typeof LoansNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsUserIdRoute: typeof AdminClientsUserIdRoute
  AdminTransfersNewRoute: typeof AdminTransfersNewRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$transferId': {
      id: '/transfers/$transferId'
      path: '/$transferId'
      fullPath: '/transfers/$transferId'
      preLoaderRoute: typeof TransfersTransferIdRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/loans/new': {
      id: '/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof LoansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$loanId': {
      id: '/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof LoansLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/admin/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loans': {
      id: '/admin/loans'
      path: '/admin/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/admin/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transfers/new': {
      id: '/admin/transfers/new'
      path: '/admin/transfers/new'
      fullPath: '/admin/transfers/new'
      preLoaderRoute: typeof AdminTransfersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/$userId': {
      id: '/admin/clients/$userId'
      path: '/admin/clients/$userId'
      fullPath: '/admin/clients/$userId'
      preLoaderRoute: typeof AdminClientsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TransfersRouteChildren {
  TransfersTransferIdRoute: typeof TransfersTransferIdRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
}

const TransfersRouteChildren: TransfersRouteChildren = {
  TransfersTransferIdRoute: TransfersTransferIdRoute,
  TransfersIndexRoute: TransfersIndexRoute,
}

const TransfersRouteWithChildren = TransfersRoute._addFileChildren(
  TransfersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  TransfersRoute: TransfersRouteWithChildren,
  AdminLoansRoute: AdminLoansRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  LoansLoanIdRoute: LoansLoanIdRoute,
  LoansNewRoute: LoansNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsUserIdRoute: AdminClientsUserIdRoute,
  AdminTransfersNewRoute: AdminTransfersNewRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
